// <auto-generated />
using System;
using ElectronicComponentInventSyst.BLL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectronicComponentInventSyst.BLL.Migrations
{
    [DbContext(typeof(ElectronicComponentInventoryDbContext))]
    [Migration("20211218130506_ClasificatorClass")]
    partial class ClasificatorClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ElectronicComponentInventSyst.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ElectronicComponentInventSyst.Entity.ElectronicComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FootprintId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.Property<string>("StockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FootprintId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("ElectronicComponents");
                });

            modelBuilder.Entity("ElectronicComponentInventSyst.Entity.Footprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Footprints");
                });

            modelBuilder.Entity("ElectronicComponentInventSyst.Entity.StoragaLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoragaLocations");
                });

            modelBuilder.Entity("ElectronicComponentInventSyst.Entity.ElectronicComponents", b =>
                {
                    b.HasOne("ElectronicComponentInventSyst.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("ElectronicComponentInventSyst.Entity.Footprint", "Footprint")
                        .WithMany()
                        .HasForeignKey("FootprintId");

                    b.HasOne("ElectronicComponentInventSyst.Entity.StoragaLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId");

                    b.Navigation("Category");

                    b.Navigation("Footprint");

                    b.Navigation("StorageLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
